Traceback (most recent call last):
  File "rul_phm08.py", line 172, in <module>
    mode = sys.argv[2]
IndexError: list index out of range
